# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3569d3237dd1681ea9fed05a0d6dfcaaae39cb6bcb3f3e636d858fa9b048c9f2aac93d63faa3c99bcf70503322a7dc3d0117cf441bec022c16bdffbc1d32276e

test:
  secret_key_base: 65abb1e811bd9677b73179317c92c8766605b73b1ec49dbd7fc0bdf4c0ce19ce0db1a1d90103c149066254cdce6bea401e5879ea166aa0d7a83268ed321b789d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
